
package new_projeto_streetfighter;

public class Select_Lutas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Select_Lutas.class.getName());

    public Select_Lutas() {
        initComponents();
    }

    public static void iniciar(){        

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelRyu = new javax.swing.JLabel();
        jLabelKen = new javax.swing.JLabel();
        jLabelGuile = new javax.swing.JLabel();
        jLabelBison = new javax.swing.JLabel();
        jLabelChunLi = new javax.swing.JLabel();
        jLabelCammy = new javax.swing.JLabel();
        jbRyu = new javax.swing.JButton();
        jbKen = new javax.swing.JButton();
        jbBison = new javax.swing.JButton();
        jbGuile = new javax.swing.JButton();
        jbCammy = new javax.swing.JButton();
        jbChunLi = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelTopoTitulo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelPlayer1 = new javax.swing.JLabel();
        txfPlayer1 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabelPlayer2 = new javax.swing.JLabel();
        txfPlayer2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(69, 69, 250));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelRyu.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabelRyu.setForeground(new java.awt.Color(89, 39, 235));
        jLabelRyu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_SF2/ryu3.png"))); // NOI18N

        jLabelKen.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabelKen.setForeground(new java.awt.Color(89, 39, 235));
        jLabelKen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_SF2/ken3.png"))); // NOI18N

        jLabelGuile.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabelGuile.setForeground(new java.awt.Color(89, 39, 235));
        jLabelGuile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_SF2/guile3.png"))); // NOI18N

        jLabelBison.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabelBison.setForeground(new java.awt.Color(89, 39, 235));
        jLabelBison.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_SF2/bison3.png"))); // NOI18N

        jLabelChunLi.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabelChunLi.setForeground(new java.awt.Color(89, 39, 235));
        jLabelChunLi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_SF2/chunli3.png"))); // NOI18N

        jLabelCammy.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabelCammy.setForeground(new java.awt.Color(89, 39, 235));
        jLabelCammy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_SF2/cammy3.png"))); // NOI18N

        jbRyu.setBackground(new java.awt.Color(153, 153, 153));
        jbRyu.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jbRyu.setForeground(new java.awt.Color(105, 19, 149));
        jbRyu.setText("Ryu");
        jbRyu.addActionListener(this::jbRyuActionPerformed);

        jbKen.setBackground(new java.awt.Color(153, 153, 153));
        jbKen.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jbKen.setForeground(new java.awt.Color(105, 19, 149));
        jbKen.setText("Ken");
        jbKen.addActionListener(this::jbKenActionPerformed);

        jbBison.setBackground(new java.awt.Color(153, 153, 153));
        jbBison.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jbBison.setForeground(new java.awt.Color(105, 19, 149));
        jbBison.setText("M.Bison");
        jbBison.addActionListener(this::jbBisonActionPerformed);

        jbGuile.setBackground(new java.awt.Color(153, 153, 153));
        jbGuile.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jbGuile.setForeground(new java.awt.Color(105, 19, 149));
        jbGuile.setText("Guile");
        jbGuile.addActionListener(this::jbGuileActionPerformed);

        jbCammy.setBackground(new java.awt.Color(153, 153, 153));
        jbCammy.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jbCammy.setForeground(new java.awt.Color(105, 19, 149));
        jbCammy.setText("Cammy");
        jbCammy.addActionListener(this::jbCammyActionPerformed);

        jbChunLi.setBackground(new java.awt.Color(153, 153, 153));
        jbChunLi.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jbChunLi.setForeground(new java.awt.Color(105, 19, 149));
        jbChunLi.setText("Chun-li");
        jbChunLi.addActionListener(this::jbChunLiActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelRyu, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbRyu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelGuile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelBison, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelChunLi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelCammy, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelKen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbGuile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbKen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbBison, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbChunLi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbCammy, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(73, 73, 73))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelRyu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbRyu, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelKen)
                    .addComponent(jbKen, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGuile)
                    .addComponent(jbGuile, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBison)
                    .addComponent(jbBison, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelChunLi)
                    .addComponent(jbChunLi, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCammy)
                    .addComponent(jbCammy, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );

        jPanel2.setBackground(new java.awt.Color(231, 231, 231));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelTopoTitulo.setFont(new java.awt.Font("Bookman Old Style", 3, 48)); // NOI18N
        jLabelTopoTitulo.setForeground(new java.awt.Color(69, 69, 250));
        jLabelTopoTitulo.setText("Escolha seu Lutador");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTopoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabelTopoTitulo)
                .addGap(26, 26, 26))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setToolTipText("");

        jLabelPlayer1.setFont(new java.awt.Font("Bookman Old Style", 3, 36)); // NOI18N
        jLabelPlayer1.setForeground(new java.awt.Color(105, 19, 149));
        jLabelPlayer1.setText("Player 1");

        txfPlayer1.setEditable(false);
        txfPlayer1.setBackground(new java.awt.Color(0, 0, 0));
        txfPlayer1.setForeground(new java.awt.Color(255, 255, 255));
        txfPlayer1.addActionListener(this::txfPlayer1ActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txfPlayer1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabelPlayer1)
                .addGap(18, 18, 18)
                .addComponent(txfPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setToolTipText("");

        jLabelPlayer2.setFont(new java.awt.Font("Bookman Old Style", 3, 36)); // NOI18N
        jLabelPlayer2.setForeground(new java.awt.Color(105, 19, 149));
        jLabelPlayer2.setText("Player 2");

        txfPlayer2.setEditable(false);
        txfPlayer2.setBackground(new java.awt.Color(0, 0, 0));
        txfPlayer2.setForeground(new java.awt.Color(255, 255, 255));
        txfPlayer2.addActionListener(this::txfPlayer2ActionPerformed);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txfPlayer2, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabelPlayer2)
                .addGap(18, 18, 18)
                .addComponent(txfPlayer2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbChunLiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbChunLiActionPerformed
        Lutador p5 = new Lutador("Chun-Li","China",30,1.69,55,null,0,0,0);
        p5.apresentar();
    }//GEN-LAST:event_jbChunLiActionPerformed

    private void jbCammyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCammyActionPerformed
        Lutador p6 = new Lutador("Cammy","Reino Unido",27,1.64,61,null,0,0,0);
        p6.apresentar();
    }//GEN-LAST:event_jbCammyActionPerformed

    private void jbGuileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuileActionPerformed
        Lutador p3 = new Lutador("Guile","Estados Unidos",45,1.82,86,null,0,0,0);
        p3.apresentar();
    }//GEN-LAST:event_jbGuileActionPerformed

    private void jbBisonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBisonActionPerformed
        Lutador p4 = new Lutador("Bison","Tailândia",55,1.82,110,null,0,0,0);
        p4.apresentar();
    }//GEN-LAST:event_jbBisonActionPerformed

    private void jbKenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbKenActionPerformed
        Lutador p2 = new Lutador("Ken","Estados Unidos",33,1.79,75,null,0,0,0);
        
        p2.apresentar();
    }//GEN-LAST:event_jbKenActionPerformed

    private void jbRyuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRyuActionPerformed
        Lutador p1 = new Lutador("Ryu","Japão",35,1.75,71,null,0,0,0);

        String nome1 = String.valueOf("-- Nome: "+p1.getNome()+" --");
        String nacional2 = String.valueOf("Nacionalidade: "+p1.getNacionalidade());
        String idade3 = String.valueOf("Idade: "+p1.getIdade());
        String altura4 = String.valueOf("Altura: "+p1.getAltura());
        String peso5 = String.valueOf("Peso: "+p1.getPeso());
        String categor6 = String.valueOf("Categoria: "+p1.getCategoria());

        txfPlayer1.setText(nome1+"\n"+nacional2+"\n"+idade3+"\n"+altura4+"\n"+peso5+"\n"+categor6);

        p1.apresentar();
    }//GEN-LAST:event_jbRyuActionPerformed

    private void txfPlayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfPlayer1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfPlayer1ActionPerformed

    private void txfPlayer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfPlayer2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfPlayer2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Lutador p1 = new Lutador("Ryu","Japão",35,1.75,71,null,0,0,0);
        Lutador p2 = new Lutador("Ken","Estados Unidos",33,1.79,75,null,0,0,0);
        Lutador p3 = new Lutador("Guile","Estados Unidos",45,1.82,86,null,0,0,0);
        Lutador p4 = new Lutador("Bison","Tailândia",55,1.82,110,null,0,0,0);
        Lutador p5 = new Lutador("Chun-Li","China",30,1.69,55,null,0,0,0);
        Lutador p6 = new Lutador("Cammy","Reino Unido",27,1.64,61,null,0,0,0);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Select_Lutas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBison;
    private javax.swing.JLabel jLabelCammy;
    private javax.swing.JLabel jLabelChunLi;
    private javax.swing.JLabel jLabelGuile;
    private javax.swing.JLabel jLabelKen;
    private javax.swing.JLabel jLabelPlayer1;
    private javax.swing.JLabel jLabelPlayer2;
    private javax.swing.JLabel jLabelRyu;
    private javax.swing.JLabel jLabelTopoTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton jbBison;
    private javax.swing.JButton jbCammy;
    private javax.swing.JButton jbChunLi;
    private javax.swing.JButton jbGuile;
    private javax.swing.JButton jbKen;
    private javax.swing.JButton jbRyu;
    private javax.swing.JTextField txfPlayer1;
    private javax.swing.JTextField txfPlayer2;
    // End of variables declaration//GEN-END:variables
}
